### PR TITLE
Minor (not quite) library improvements.

### PR DESCRIPTION
**Pull request by marcoonroad**
This PR introduces the following changes:
- Bugfix for issue #6.
- Setup for Travis-CI build.
- Channels & Threads instead manual queueing.
- Minor changes on README.
- Synchronous calls on public method self-sends (to avoid circular dependencies).

In order to be considered ready to merge, this PR must:
- [x] Pass all tests on the given compiler releases/versions (see .travis.yml).
- [x] Introduce tests covering resource cleanup for both Channels & Threads.
- [x] Introduce stress tests (kind of fork-bomb of recursively spawned actors) to see how much it scales?
- [x] Cover the synchronous self-send calls on test suite.
- [x] Documentation on README regarding synchronous self-send calls.

Some things can be discussed on other issues/PRs, for instance:
* Some kind of back-pressure/limit to avoid too much fast producers causing "starvation" and problems like that.
* A custom/optimized thread pool to scale this current implementation.

### CODE REVIEW

**Comment by marcoonroad** [comment]
The whole build history can be found here https://travis-ci.org/marcoonroad/oo-actors :link: .

**Comment by marcoonroad** [comment]
Well, I should avoid Threads. They provide no clear guidance for resource cleanup (there's only `join` to block waiting for them, no `kill` is documented except regarding `:app_lifetime` parameter).

**Comment by marcoonroad** [comment]
I have forgot entirely to document! There's some change on main module file to discard asynchronous public method calls on self-sends (they're, so, synchronous - no promises around here). It's just to avoid gotchas regarding threading issues (for example, circular dependencies).

Nevermind, I should also cover that!

**Comment by marcoonroad** [comment]
(God, there's too much things for just a bug fix - I should split off something from here.)

**Comment by marcoonroad** [comment]
Hooray. :tada: :clap: :cake: :cookie:

Everything passes. This current implementation is not scalable, tho. One thread by actor instance is a waste of resources. We need a thread pool with locks on given actor object (maybe OO::Monitors could help us here?).

I'm deferring that question to other issue/PR. This PR is too big for a bugfix intent, hahaha.

**Comment by marcoonroad** [comment]
@jnthn, could you please review and give me a feedback later, whenever you can afford some of your precious time. I'll be very grateful for that. :)

I know that your major focus is the MoarVM and the Perl 6 discussions... Also, thank you by the amazing work on the MoarVM!

:clap: :clap: :clap: :clap:

**Comment by jnthn** [comment]
Thanks for the PR, and sorry for missing it. The most immediate issue with the approach it takes it that it spawns a real OS `Thread` per actor, which would make them decidedly not lightweight, which is one of the goals. I've fixed it now.

**Pull request closed without merging**
